name: React App CI/CD

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: mendisofficial/react-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.DOCKER_IMAGE }}:latest
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE }}:buildcache
          cache-to: type=registry,ref=${{ env.DOCKER_IMAGE }}:buildcache,mode=max

      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          debug: true
          script: |
            # Docker login using existing secrets
            echo "$DOCKERHUB_TOKEN" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
            
            # Pull the latest image (will automatically pull the correct architecture)
            docker pull $DOCKER_IMAGE:latest
            
            # Stop and remove the old container if it exists
            docker stop react-app || true
            docker rm react-app || true
            
            # Wait a moment for the port to be released
            sleep 5
            
            # Run the new container
            docker run -d \
              --name react-app \
              -p 3000:80 \
              --restart unless-stopped \
              $DOCKER_IMAGE:latest
            
            # Verify the container is running
            if docker ps | grep react-app; then
              echo "React app container is running successfully!"
            else
              echo "Failed to start the React app container."
              exit 1
            fi