name: React App CI/CD

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: mendisofficial/react-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:latest

      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          debug: true
          script: |
            whoami
            echo "Current directory: $(pwd)"
            
            # Pull the latest image
            docker pull ${{ env.DOCKER_IMAGE }}:latest
            
            # Stop and remove the old container if it exists
            docker stop react-app || true
            docker rm react-app || true
            
            # Run the new container
            docker run -d \
              --name react-app \
              -p 3000:80 \
              --restart unless-stopped \
              ${{ env.DOCKER_IMAGE }}:latest
            
            # Verify the container is running
            docker ps | grep react-app